### ISSUE TITLE
Add information (in readme?) about Metadata topics for experimenters

### ISSUE THREAD

**Issue by jonakarl** [MONROE-PROJECT/Experiments#14]
Add (a curated version of?) https://secure.mlab.no/monroewiki/doku.php?id=metadataformat here so experimenters can see what topics they can subscribe to and what information will be available in each message.

**Comment by jonakarl** [comment]
Closed by commit : 053bf7af316bb33382b5f303ac6e3899ae1103ee

**Comment by jonakarl** [comment]
Sorry closed wrong issue sorry

**Comment by relet** [comment]
I have copied the metadata wiki pages into the github wiki for this repository, and removed development related paragraphs.

**Comment by relet** [comment]
https://github.com/MONROE-PROJECT/Experiments/wiki/Metadata

**Comment by relet** [comment]
If you need a converter from dokuwiki syntax, there is a converter dokuwiki2mediawiki.php inside this package which works: http://www.staerk.de/files/mediasyntax.tar.gz

**Comment by jonakarl** [comment]
Looks good to me
