### ISSUE TITLE
Experiments should not use the interface names as identifier

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/Experiments#2]
As we discussed prior to and during the demo, interface names are a poor identifier for the connection used. 

My suggestion would be to use the InterfaceId that is provided by metadata (which maps to the IMEI for modems, MAC for wifi and fixed links), and to also include the operator MCC/MNC in all results.

This issue affects all current experiments, and has to be matched on the database side.

**Comment by jonakarl** [comment]
Just to clarify:

I guess by " interface names are a poor identifier" you mean on the
database side, ie when we store the experiment result.
For setting up and starting the experiment/container interface name is
still preferred I guess.

2016-04-26 8:58 GMT+02:00 Thomas Hirsch notifications@github.com:

> Assigned #2 https://github.com/MONROE-PROJECT/Experiments/issues/2 to
> @jonakarl https://github.com/jonakarl.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/MONROE-PROJECT/Experiments/issues/2#event-641051212

## 

_Jonas Karlsson_
Senior Research Engineer

_Karlstad University_
SE-651 88 Karlstad, Sweden
Telephone: +46 54 700 15 64
Mobile: +46 70 672 06 20
Skype: karlsson.karl.jonas
Hangout: karlsson.karl.jonas

twitter.com/kau
facebook.com/karlstadsuniversitet
KAU.SE

**Comment by relet** [comment]
Yes, I agree. I only meant the reporting of results.

**Comment by jonakarl** [comment]
Closed by commit #6
