### ISSUE TITLE
install the latest version of dig to the monroe base

### ISSUE THREAD

**Issue by FoivosMichelinakis** [MONROE-PROJECT/Experiments#22]
The latest version of dig (the one found in bind version 9.11) has support for edns-client-subnet. The version found in the debian repo is 9.9 which does not include this feature. so I would have to compile and install it as part of building the container.

I guess a lot of people would be interested in the programs contained in the bind package so it would be nice to be included in the base image in any case. Thus, it would be even better to include the latest version of it as well.

A guide for building it can be found here
https://kb.isc.org/article/AA-00768/0/Getting-started-with-BIND-how-to-build-and-run-named-with-a-basic-recursive-configuration.html

**Comment by jonakarl** [comment]
I would like to keep the base as "vanilla" as possible to avoid package dependency problems but would it suffice if I installed this newer version of bind in a separate folder ie not overwriting the Debian default?

**Comment by FoivosMichelinakis** [comment]
Yes. It would be enough. Actually I only need dig, so if it is possible to remove the other tools to  reduce space, please do.

**Comment by jonakarl** [comment]
Fixed in commit : 0d0642018d748f25d54b5c1f94a18c53900f1d17
