### ISSUE TITLE
Experiments should use a GUID

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/Experiments#3]
We agreed on using a GUID for experiments. 

Open questions:
- Which schema do we use? Will that work for the scheduler, the database and the users?
- How do we include the permanent MONROE experiments in that schema? 
- How do we pass this information to the container? 

I would suggest we go for experiment_id.scheduling_id.node_id.repetition with 
- experiment_id being the full (--no-trunc) docker image id of the container
- scheduling_id being either 0 (for non-scheduled experiments) or the scheduling id (auto_incrementing integer) from the scheduler.
- node_id being the node id from the inventory
- repetition being the number of times the experiment had to be restarted (0 based)

Which gives us an experiment GUID like
9c93b52032bd9454e7e0b05b7d1011ebe6c80698b78573699464cf3136d48b0c.620.9.1

If that is the only parameter to the experiment, we could pass it on command line as it is now. As the discussion goes towards including user parameters in the scheduling, I would prefer to pass it along with all other parameters in a JSON configuration file. 

(The scheduler currently passes a parameter `--guid ${SCHEDID}.${NODEID}.${COUNT}`, while it stores deployment parameters in a JSON file. We would have to adjust both to match the decisions here.)

**Comment by jonakarl** [comment]
+1 For using a JSON file. 

this could quite easily be mapped into every container by the -v flag of the docker (probably also readonly). 
To be future proof maybe we should agree on that we always map directory in every container like we do for the outdir ... Then the json could be a predefined file in that directory like ... parameters.json 
eg. 
docker ...... -v $CONFIGDIR/ping:/monroe-config:ro

**Comment by jonakarl** [comment]
I have added a placeholder Guid in commit c30f1dc so the DB can be prepared (not deployed in prod yet
= no docker push)

**Comment by jonakarl** [comment]
Enabled for ping and http_download experiment
