### ISSUE TITLE
Measure bandwidth usage of experiments (ping, http, others in 'container 2')

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/Experiments#4]
In order to manage the bandwidth constraints and a schedule for the active experiments, we need to establish a (worst case) measure of the bandwidth requirements of all continuous/regular MONROE experiments.

The aim is to establish a schedule that ensures  the MONROE experiments do not use more than 20% of the available monthly quota.

**Comment by mikepeon** [comment]
To reduce bandwidth requirements, could it be possible to send binary data instead of JSON (less computing time both in the nodes and in the server), or maybe at least Binary JSON?

**Comment by jonakarl** [comment]
The rationale for JSON was to have a human readable format that is easily
producible from multiple programming languages.

I would say that if we should invalidate that reason (human readable
format) in an effort to optimize the importer chain, we could just as well
redo the entire chain as it is not designed for efficiency.
I would then argue that we could just as well write directly into the db
from the nodes (authenticated and, as far as I have seen, pretty small
transfers).

2016-04-29 12:22 GMT+02:00 mikepeon-imdea notifications@github.com:

> To reduce bandwidth requirements, could it be possible to send binary data
> instead of JSON (less computing time both in the nodes and in the server),
> or maybe at least Binary JSON?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/MONROE-PROJECT/Experiments/issues/4#issuecomment-215678587

## 

_Jonas Karlsson_
Senior Research Engineer

_Karlstad University_
SE-651 88 Karlstad, Sweden
Telephone: +46 54 700 15 64
Mobile: +46 70 672 06 20
Skype: karlsson.karl.jonas
Hangout: karlsson.karl.jonas

twitter.com/kau
facebook.com/karlstadsuniversitet
KAU.SE

**Comment by kristrev** [comment]
Please provide an estimate for how much you believe can be saved by transferring binary data. rsync is used and I assume compression is enabled, and human readable JSON is easy to compress. I also don't buy that you save compute time, you would still to convert from binary data to whatever format the database expects.

**Comment by jonakarl** [comment]
In the F2F in Oslo we talked about minimizing the amount quota eaten up by experiment results, which I think is slightly different from this issue which I feel is more about not doing huge experiments (ie downloading a 1TB file once every hour to test MBB Speed) 

To get forward should we split this issue in one for active experiment data and one for the transfering of results ?

**Comment by relet** [comment]
This issue is about measuring what we use today. If you want to optimise, please create a separate issue, yes :)

**Comment by jonakarl** [comment]
Closed due to inactivity.
