### ISSUE TITLE
Experiments should be resilient to network issues, update metadata

### ISSUE THREAD

**Issue by relet** [MONROE-PROJECT/Experiments#5]
Interfaces on the node may disappear, be reset or re-established, resulting in ENODEV errors in applications that are bound to the interface, and possibly other error codes.

Experiments should detect whenever an interface (or the interface an experiment is assigned to) disappears. 

They should also detect when it appears, and wait for an update from the metadata broadcast to establish the link to the InterfaceId and operator before publishing further results.

**Comment by jonakarl** [comment]
Implemented in the ping container/experiment. 
Partially implemented in the http_download (there is no easy way to recover if the interface disappears in the middle of the transaction so I simply abort the experiment on that interface).
